### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by antonioolf** [antonioolf/cdi#5]
- [x] [Bug] Back to first selection position when reach the end of folders list and vice versa

- [x] [Bug] Fix problem with spaced names in folders

- [ ] [Improvement] Filter folders by typing keyboard letters
- [ ] [Improvement] Abstract stylization of text in functions
- [ ] [Improvement] Add more comments
